#!/usr/bin/perl

use File::Copy;

$outputDir = "./pps-log/";
$outputFile = $outputDir . "PPS-Unity.log";

`mkdir -p \'$outputDir\' > /dev/null 2> /dev/null`;

open PPS_LOG, ">", $outputFile or die("Cannot create new $outputFilei: $!\n");
$currDir = `pwd`;
chomp($currDir);

print PPS_LOG "CurDir=[" . $currDir . "]\n";

$StagingAssets = $currDir . "/Temp/StagingArea/assets";
$UnityLibAssets  = $currDir . "/../../Eclipse/Unity35-Lib/assets";
$PPSSDKDemoAssets = $currDir . "/../../Eclipse/PPSSDKDemoUnity/assets";
$PPSSDKDemoAssetsSrc = $currDir . "/../../Eclipse/PPSSDKDemoUnity-src/assets";

print PPS_LOG "cp -R \'$StagingAssets\' \'$UnityLibAssets\'\n";
print PPS_LOG "cp -R \'$StagingAssets\' \'$PPSSDKDemoAssets\'\n";
print PPS_LOG "cp -R \'$StagingAssets\' \'$PPSSDKDemoAssetsSrc\'\n";

`cp -R \'$StagingAssets\' \'$UnityLibAssets\'`;
`cp -R \'$StagingAssets\' \'$PPSSDKDemoAssets\'`;
`cp -R \'$StagingAssets\' \'$PPSSDKDemoAssetsSrc\'`;

##Make hard links to PPSUnity C# files from unity Project to repo

print PPS_LOG "cp -Rf ./Assets/Plugins/PlayPhoneMultiNetUnity/* ../../../PlayPhoneMultiNetUnity/\n";
print PPS_LOG "cp -Rf ./Assets/Plugins/Android/src/com/playphone/multinet/unity/* ../../../UnityWrapperAndroid/src/com/playphone/multinet/unity/\n";
print PPS_LOG  "cp ./Assets/Plugins/Android/*.jar ../../Eclipse/Unity35-Lib/plugins\n";
`cp -Rf ./Assets/Plugins/PlayPhoneMultiNetUnity/* ../../../PlayPhoneMultiNetUnity/`;
`cp -Rf ./Assets/Plugins/Android/src/com/playphone/multinet/unity/* ../../../UnityWrapperAndroid/src/com/playphone/multinet/unity/`;
`cp ./Assets/Plugins/Android/*.jar ../../Eclipse/Unity35-Lib/plugins`;

print PPS_LOG `printenv`;
close PPS_LOG . "\n";


